### ISSUE TITLE
Implement a Setting area

### ISSUE THREAD

**Issue by nerone-github** [nerone-github/UnleashedAudioPlayer#4]
Possible customization options:

- Theme, Color selection to match the car's other UI/Dash colors
- Hide certain albums/sound files

**Comment by Tiemichael** [comment]
Another idea could be different way of sorting the albums (date / album-name / genre / reverse-sort)
Thanks!

**Comment by nerone-github** [comment]
I have commited a way to save settings, and also the theme selection is now possible. I will close this issue now as it is too unspecific. 

For each setting a new issue should be created to have a better track of which settings are implemented already and which not.

@Tiemichael #6 is suited for your request, i will change the title accordingly
