### ISSUE TITLE
AZ-Button

### ISSUE THREAD

**Issue by Tiemichael** [nerone-github/UnleashedAudioPlayer#5]
Thank you for providing these extra buttons!
When pressing the AZ-button, for me an extra line with only one button '2' comes up, which  cannot be selected (same on phone and in car)
(I assume it should show the 1st letter of each available album, but not so sure)

## Platform(s)

Please provide this information if this is a bug report. If it is a feature request you can remove this section.

  - Phone brand and model: Xiaomi A1
  - Android version (stock/custom) and version: 8.0
  - Car Brand Model and year: Opel Astra 2017

**Comment by nerone-github** [comment]
Hey it shows the first letter of each available artist. Do you have only one? Are all albums tagged correctly or is there an artist missing?

**Comment by Tiemichael** [comment]
I have app 100 albums, need to check if all are tagged correctly ...

**Comment by nerone-github** [comment]
Yeah - i've done a test, removed artist from one of the albums, and the index is not being populated correctly.

So now i've changed the default value for missing artist or name to "⁇" which should make it also easier to identify wrong tags. They will be shown at the end of the album list.

Thanks for reporting!
