### ISSUE TITLE
Stop Playing

### ISSUE THREAD

**Issue by Tiemichael** [nerone-github/UnleashedAudioPlayer#7]
Hi,
over the last 2 weeks I encounter cases when UnleashedAudioPlayer simple stops playing. If I select another song, I starts playing again for a few seconds and stops again.
I don't think it's a 'connection issue', as Google PlayMusic and DoubleTwist don't show any issue.
This issue seems unchanged over the last couple of builds.
Force-Stop the app and clearing cache does not help, but after rebooting the phone it's working again for a few days / trips.
Thank you, for this nice app!

## Platform(s)

Please provide this information if this is a bug report. If it is a feature request you can remove this section.

  - Phone brand and model: Xiaomi A1
  - Android version (stock/custom) and version: 8.0 (stock)
  - Car Brand Model and year: Opel Astra 2017

**Comment by nerone-github** [comment]
Hi, can you please check if you entered the "Unleashed Audio" Entry in the "Media Tab" first before switching to the OEM tab? This is necessary to make sure that it gets the Control for the media buttons. If this step is skipped it might be that GPM or a different App takes the focus from the OEM Tab

**Comment by Tiemichael** [comment]
Thank you!
Most of the time I started Unleashed via the OEM-tab directly.
Will try over the next few days using the Media-Tab first

**Comment by Tiemichael** [comment]
Ok, chages to 'do not optimize' for both ... let's wait and see
Thanks!

**Comment by nerone-github** [comment]
I think the error should not appear again so i close it. If it still happens feel free to answer and or reopen :)
